[creativeModeTabs]
	enableCreativeModeTabs = true
	syncSelectedCreativeModeTab = true
	disabledCreativeModeTabs = ["minecraft:op_blocks"]
	showCreativeTabNameInSearchbar = false

[stackGroups]
	enableStackGroups = true
	enableCreateStackGroupButton = true
