name = "Spiced Cider"
author = "Evan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "071f3263c43d3b5c214d5000a5ac48076c01fbceebf1557a664cffc5e762ab5e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
unsup = "1.1.6"

[options]
acceptable-game-versions = []
