name = "Spiced Cider"
author = "Evan"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "06ad8ae05305b3a323ced1a06b629de05eb18d62d7a296cf1b7bba38b1de814b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.230"
unsup = "1.1.6"

[options]
acceptable-game-versions = ["1.21", "1.21–1.21.3"]
