version=1
preset=minecraft
source_format=packwiz

# TODO: point to github pages pack.toml
source=https://evanbones.github.io/Spiced-Cider/pack.toml

[branding]
modpack_name=Spiced Cider

[colors]
progress=E15817
button=E15817
background=263238
